#!/bin/sh

###
## Remove stuff
###

sudo apt-get remove --purge -y rhythmbox
sudo apt-get autoremove --purge -y
sudo apt-get autoclean

###
## Update stuff
###

sudo apt-get -y update
sudo apt-get -y dist-upgrade --show-upgraded


###
## Standard pkgs
###

# Base tools
$CWD/app-install build-essential;
$CWD/app-install python;
$CWD/app-install net-tools;
$CWD/app-install lm-sensors;
$CWD/app-install git;
$CWD/app-install zsh;
$CWD/app-install openssl;
$CWD/app-install apt-transport-https;

if [ $SETUP_TYPE = "desktop" ]; then

    # Internet
    $CWD/chrome-install

    # Desktop setup helpers
    $CWD/app-install dconf-tools
    $CWD/app-install gnome-tweak-tool

    # Misc
    $CWD/app-install ttf-mscorefonts-installer
    $CWD/app-install ffmpeg

    # UI/media
    $CWD/app-install smplayer
    $CWD/app-install gimp
    $CWD/app-install inkscape
    $CWD/app-install audacity
    $CWD/app-install blender

    # File manager
    $CWD/app-install exo-utils

    #if [ -f "/usr/bin/nautilus" ]; then
    #    PCMAN_POST="sudo mv /usr/bin/nautilus /usr/bin/nautilus.bak"
    #    PCMAN_POST="${PCMAN_POST} && sudo ln -s /usr/bin/pcmanfm /usr/bin/nautilus"
    #else
    #    PCMAN_POST=""
    #fi;

    #$CWD/app-install pcmanfm "${PCMAN_POST}"

    $CWD/app-install pcmanfm

    # -- Dev UI tools

    # Sublime text
    SUBL_PRE="wget -qO - 'https://download.sublimetext.com/sublimehq-pub.gpg' | sudo apt-key add -";
    SUBL_PRE="${SUBL_PRE} && echo 'deb https://download.sublimetext.com/ apt/stable/' | sudo tee /etc/apt/sources.list.d/sublime-text.list"
    SUBL_PRE="${SUBL_PRE} && sudo apt-get update"

    SUBL_POST="mkdir -p ${HOME}/.config/sublime-text-3/Packages/User"

    $CWD/app-install sublime-text "${SUBL_POST}" "${SUBL_PRE}"

fi;


###
## Common pkgs
###

# -- Servers
$CWD/app-install redis-server
$CWD/app-install nginx
$CWD/app-install ufw

# Postgresql
PG_POST="sudo update-rc.d postgresql enable && sudo service postgresql start"
$CWD/app-install postgresql "${PG_POST}"



###
## Other/extra?
###

[ $SETUP_TYPE = "server" ] && $CWD/app-install letsencrypt;


echo "\n\nSuccessful packages:\n-------------\n"
[ -e /tmp/.app-install-success.log ] && cat /tmp/.app-install-success.log;

echo "\n\nFAILED packages:\n-------------\n"
[ -e /tmp/.app-install-fail.log ] && cat /tmp/.app-install-fail.log;
