#!/bin/sh


echo "Gnome settings (keyboard delay, scrollbars?, etc)"

echo "Turn off mouse accel"
xset m 8/8 0

# Keyboard repeat speed (interval in ms between characters)
echo "Keyboard repeat interval (previous): $(gsettings get org.gnome.desktop.peripherals.keyboard repeat-interval)"
gsettings set org.gnome.desktop.peripherals.keyboard repeat-interval 10
echo "Keyboard repeat interval (new): $(gsettings get org.gnome.desktop.peripherals.keyboard repeat-interval)"

# Keyboard input delay
echo "Keyboard delay (previous): $(gsettings get org.gnome.desktop.peripherals.keyboard delay)"
gsettings set org.gnome.desktop.peripherals.keyboard delay 180
echo "Keyboard delay (new): $(gsettings get org.gnome.desktop.peripherals.keyboard delay)"


### Below doesn't seem to be needed in Ubuntu 18.04 somehow (after the rest of init has been ran at least)


## Backup original environment file
# sudo cp /etc/environment /etc/environment.bak

## Hopefully disable overlay scrollbars
# ENV_FILE_CONTENT=$(cat /etc/environment | grep -v "^GTK_OVERLAY_SCROLLING=.*$")
# echo "${ENV_FILE_CONTENT}\nGTK_OVERLAY_SCROLLING=0" | sudo tee /etc/environment;
