#!/bin/sh

wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | apt-key add -
apt-get install -y apt-transport-https
echo "deb https://artifacts.elastic.co/packages/5.x/apt stable main" | tee -a /etc/apt/sources.list.d/elastic-5.x.list

apt-get update
apt-get install -y elasticsearch

/bin/systemctl daemon-reload
/bin/systemctl enable elasticsearch.service

systemctl start elasticsearch.service

