#!/bin/sh

BACKPORTS=/etc/apt/sources.list.d/backports.list
FAILCONF=/etc/fail2ban/fail2ban.local
JAILCONF=/etc/fail2ban/jail.local

if [ ! -s $BACKPORTS ]; then
    echo "deb http://ftp.debian.org/debian jessie-backports main" | sudo tee $BACKPORTS
fi

sudo apt-get update
sudo apt-get upgrade -y

# Basic needs
sudo apt-get install -y zsh build-essential linux-headers-amd64 nginx git software-properties-common python python-software-properties openssl iptables-persistent fail2ban sendmail-bin sendmail

# Let's Encrypt
sudo apt-get install -y certbot -t jessie-backports

# Some fail2ban setup
if [ ! -s $FAILCONF ]; then
    sudo cp /etc/fail2ban/fail2ban.conf $FAILCONF
fi
if [ ! -s $JAILCONF ]; then
    sudo cp /etc/fail2ban/jail.conf $JAILCONF
fi

