#!/bin/sh

SETUP_TYPE=$1
[ -z "$SETUP_TYPE" ] && SETUP_TYPE="desktop";

if [ $SETUP_TYPE != "desktop" ]; then
    if [ $SETUP_TYPE != "server" ]; then
        echo "Usage: sudo ./init [desktop|server]\n"
        echo "Failed setting up system - unknown type \"${SETUP_TYPE}\"";
        exit 1;
    fi;
fi;

if [ ! -e /root/.profile ]; then
    echo "Usage: sudo ./init [desktop|server]\n"
    echo "Failed setting up ${SETUP_TYPE} - run with sudo";
    exit 1;
fi;


# -------------- START SYSTEM SETUP --------------- #


echo "" > /tmp/.app-install-success.log
echo "" > /tmp/.app-install-fail.log

###
## Disable swap
###

if [ $SETUP_TYPE="desktop" ]; then
    ./disable-swap
fi;

###
## Update stuff
###

apt-get -y update
apt-get -y upgrade --show-upgraded


###
## Standard pkgs
###

# Base tools
./app-install build-essential;
./app-install python;
./app-install git;
./app-install zsh;
./app-install openssl;
./app-install apt-transport-https;

if [ $SETUP_TYPE="desktop" ]; then

    ./app-install dconf-tools

    # Misc
    ./app-install ttf-mscorefonts-installer
    ./app-install ffmpeg

    # UI/media
    ./app-install smplayer
    ./app-install gimp
    ./app-install inkscape
    ./app-install audacity
    ./app-install blender

    # File manager
    ./app-install exo-utils

    if [ -f "/usr/bin/nautilus" ]; then
        PCMAN_POST="mv /usr/bin/nautilus /usr/bin/nautilus.bak"
        PCMAN_POST="${PCMAN_POST} && ln -s /usr/bin/pcmanfm /usr/bin/nautilus"
    else
        PCMAN_POST=""
    fi;

    ./app-install pcmanfm $PCMAN_POST

fi;

# -- Dev UI tools

if [ $SETUP_TYPE="desktop" ]; then

    # Sublime text\
    SUBL_PRE="wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -";
    SUBL_PRE="${SUBL_PRE} && echo 'deb https://download.sublimetext.com/ apt/stable/' | sudo tee /etc/apt/sources.list.d/sublime-text.list"
    SUBL_PRE="${SUBL_PRE} && apt-get update"
    ./app-install sublime-text "" $SUBL_PRE

fi;

# -- Servers
./app-install redis-server
./app-install nginx

# Postgresql
PG_POST="update-rc.d postgresql enable && service postgresql start"
./app-install postgresql $PG_POST

if [ $SETUP_TYPE="server" ]; then

    ./app-install letsencrypt

fi;

###
## Terminal setup-ish
###

# copy over configs and bin scripts
./copy-files


###
## Some GNOME settings
###

[ $SETUP_TYPE="desktop" ] && ./gnome-settings;

###
## Create the new ssh keys
###

echo "\n\nSuccessful packages:\n-------------\n"
[ -e /tmp/.app-install-success.log ] && cat /tmp/.app-install-success.log;

echo "\n\nFAILED packages:\n-------------\n"
[ -e /tmp/.app-install-fail.log ] && cat /tmp/.app-install-fail.log;

echo "\n\n=========\n===========\n\n...Done (hopefully)\n\n";

exit 0;
