#!/bin/sh

SETUP_TYPE="$1"
[ -z "$SETUP_TYPE" ] && SETUP_TYPE="desktop";

if [ $SETUP_TYPE != "desktop" ]; then
    if [ $SETUP_TYPE != "server" ]; then
        echo "Usage: ./init [desktop|server]\n"
        echo "Failed setting up system - unknown type \"${SETUP_TYPE}\"";
        exit 1;
    fi;
fi;

CWD=$(cd -P -- "$(dirname -- "$0")" && pwd -P)

# -------------- START SYSTEM SETUP --------------- #


echo "" > /tmp/.app-install-success.log
echo "" > /tmp/.app-install-fail.log

###
## Disable swap
###

if [ $SETUP_TYPE = "desktop" ]; then
    $CWD/disable-swap
fi;


###
## Install apps
###

$CWD/apps $SETUP_TYPE


###
## Terminal setup-ish
###

# copy over configs and bin scripts
$CWD/copy-files


if [ $SETUP_TYPE = "server" ]; then

    # nano syntax highlighting
    [ -f "${CWD}/setup-nano-syntax-highlighting" ] && $CWD/setup-nano-syntax-highlighting || echo "File missing - setup-nano-syntax-highlighting";

fi;


###
## Some GNOME settings
###

[ $SETUP_TYPE = "desktop" ] && $CWD/gnome-settings;

###
## Create the new ssh keys
###


## ----


echo "\n\n=========\n===========\n\n...Done (hopefully)\n\n";

exit 0;
