#!/bin/zsh

# Download highlighter files
if [ ! -d /usr/share/nano-syntax-highlighting ]; then
    sudo git clone https://github.com/scopatz/nanorc.git /usr/share/nano-syntax-highlighting/
fi

# Create new .nanorc file
cp ../.nanorc /tmp

# Get every file available to put in .nanorc
ls /usr/share/nano-syntax-highlighting/*.nanorc > /tmp/nanorc-files

while IFS= read -r nanofile
    do
        echo "include $nanofile" >> /tmp/.nanorc
    done < "/tmp/nanorc-files"


# Put .nanorc in user and root dirs
sudo cp /tmp/.nanorc /root
cp /tmp/.nanorc $HOME/

# Clean up
# rm /tmp/{.nanorc,nanorc-files}
