#!/bin/sh

# Package keys

apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
echo "deb http://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

# Package updates

apt-get update

# Package installs

apt-get install -y yarn

# Clean-up

apt-get autoclean
apt-get clean

